### ISSUE TITLE
Two issue about libary

### ISSUE THREAD

**Issue by HuuNguyen312** [YummyLau/PanelSwitchHelper#101]
I faced 2 issues
- Can't scroll to first message "模拟数据第 1"
![device-2020-10-02-133826](https://user-images.githubusercontent.com/9895294/94894961-9aa41100-04b4-11eb-817e-6ed8639ca637.png)

- When clicking into search input, the result layout will display instead of input chat. But the result layout is hidden below the keyboard.

![device-2020-10-02-135913](https://user-images.githubusercontent.com/9895294/94896445-afce6f00-04b7-11eb-9e5e-413af63fc231.png)

Please help me resolve it to the 
![device-2020-10-02-135913](https://user-images.githubusercontent.com/9895294/94896564-020f9000-04b8-11eb-8738-f3a5c6d35d53.png)
expected result

Thanks

**Comment by YummyLau** [comment]
@HuuNguyen312 

For the first question: Since you have added Search ui, you should take the new height of Search ui into consideration when calculating the sliding distance.

For the second question: the framework needs to bind an EditText as an input source, and the unbound input source pulls up the input method framework and does not automatically process it, and needs to be extended.

**Comment by YummyLau** [comment]
@HuuNguyen312 The solution to the second problem: It may be possible to extend the framework capabilities, such as supporting the binding of multiple input source controls. Currently under evaluation. Or you can remove the original input source control from the original ViewGroup and re-add it to the new ViewGroup.

**Comment by YummyLau** [comment]
@HuuNguyen312 
The v1.3.10 version was released today, you can upgrade the version to solve the second problem.

**Comment by HuuNguyen312** [comment]
> @HuuNguyen312
> The v1.3.10 version was released today, you can upgrade the version to solve the second problem.

@YummyLau Thanks for your support.
The second problem is solved by the addSecondaryInputView method

The first problem also occurs in your sample. I can't scroll to the first message 
Please view the video: https://streamable.com/l1i9hp

**Comment by YummyLau** [comment]
@HuuNguyen312 

I seemed to understand what you meant wrong before, I thought SearchUI was blocking part of your layout. In fact, the behavior shown by the Demo is normal, because the content of the list is laid out to a height by the frame, which refers to the interaction of WeChat. This is to smooth the display of the transition panel. You can freely control it by using api addContentScrollMeasurer

```
       .addContentScrollMeasurer(new ContentScrollMeasurer() {
                        @Override
                        public int getScrollDistance(int defaultDistance) {
                            return xxxx;  //Dynamic calculation
                        }

                        @Override
                        public int getScrollViewId() {
                            return R.id.recycler_view;
                        }
                    })
```

**Comment by HuuNguyen312** [comment]
@YummyLau 

I tried the method you suggested
I can only scroll to the first message when return getScrollDistance = 0.
Unfortunately, I can't scroll to the last message
Please view the video: https://streamable.com/oa3xjx

Please help me resolve it.
Thanks

**Comment by YummyLau** [comment]
@HuuNguyen312 HU

Because the height of the list in the content area has not changed, adjusting the return value of getScrollDistance only determines that the starting point of the top and bottom layout of the layout is different.
If you need the height of the list to change dynamically（it likes LienarLayout-weight), you may sacrifice the fluency of switching. You can turn off the sliding with contentScrollOutsideEnable(false), but it is generally not recommended.

Note: The library refers to a large number of IM apps. Generally, when the panel is pulled up, the sliding behavior should close the panel.

Hope it helps you.

**Comment by YummyLau** [comment]
@HuuNguyen312 
Last night, I discussed with your friends on WeChat about the problem you said.
In fact, according to the trend of android11, the official processing of window changes is to implement transition animation for the translation business layout, so it is not recommended to dynamically change the height of the list when a panel appears. So sliding the list when the panel is displayed is a bad interaction. When the panel is displayed, sliding should give priority to the panel. This is just our recommendation.
